# SFT full training onn RLHF dataset

python sft.py \
    --model_name_or_path google/gemma-2-2b \
    --dataset_name HuggingFaceH4/ultrafeedback_binarized \
    --dataset_train_split train_sft \
    --dataset_test_split test_sft \
    --dataset_text_field chosen \
    --output_dir logs/sft \
    --torch_dtype bfloat16 \
    --attn_implementation eager \
    --learning_rate=1.41e-5 \
    --per_device_train_batch_size=8 \
    --gradient_accumulation_steps=128 \
    --gradient_checkpointing \
    --logging_steps=1 \
    --num_train_epochs=3 \
    --max_steps=-1 \
    --eval_strategy steps \
    --eval_steps 20 \
    --save_steps 20 \
    --load_best_model_at_end \
    --report_to wandb \
    --push_to_hub True \
    --bf16 \
    --logging_first_step \
    --use_peft \
    --load_in_4bit \
    --lora_r 128 \
    --lora_alpha 128 \
    --lora_dropout 0.05 \
    --lora_target_modules q_proj k_proj v_proj o_proj gate_proj up_proj down_proj